import Head from 'next/head'

import EmojiContainer from './components/emoji_container/emoji_container'
import MainFooter from './components/main_foot/main_footer'
import MainNavigation from './components/main_nav/main_nav'

export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNavigation></MainNavigation>

      <main>
        
        <EmojiContainer></EmojiContainer>

      </main>

      <MainFooter></MainFooter>

    </>
  )
}